export const assets = {
  Hat: 'hat.png',
  Dino: 'dino.png',
  girl1: './spritesheet/girl1.png',
  girl2: './spritesheet/girl2.png',
  girl3: './spritesheet/girl3.png',
  girl4: './spritesheet/girl4.png',
  girl5: './spritesheet/girl5.png',
  girl6: './spritesheet/girl6.png',
  girl7: './spritesheet/girl7.png',
  girl8: './spritesheet/girl8.png',
  card1: './ui/Card1.png',
  card2: './ui/Card2.png',
  btnActive: './ui/btn/btn-active.png',
  btnDisable: './ui/btn/btn-disable.png',
  btnHover: './ui/btn/btn-hover.png',
  btnNormal: './ui/btn/btn-normal.png',
  iconPlus: './ui/icons/01.png',
};
